# Generated by Django 4.0.6 on 2022-09-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/about/')),
            ],
            options={
                'verbose_name': 'Biz haqimizda',
                'verbose_name_plural': 'Biz haqimizda',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('person', models.IntegerField()),
                ('title', models.TextField(max_length=100)),
                ('image', models.ImageField(upload_to='media/Courses/')),
                ('mark', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='Homepage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/home/')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
            },
        ),
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('data', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
            ],
            options={
                'verbose_name': 'Guruh',
                'verbose_name_plural': 'Guruhlar',
            },
        ),
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Royxatdan o`tish`',
                'verbose_name_plural': 'Ro`yxatgan o`tganlar',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('text', models.TextField(max_length=200)),
                ('section', models.TextField(max_length=50)),
                ('image', models.ImageField(upload_to='media/subjects/')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_nomber', models.IntegerField()),
                ('section', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/subjects/')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jobs', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
            ],
            options={
                'verbose_name': 'O`qituvchi',
                'verbose_name_plural': 'O`qituvchilar',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
                ('lavel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professorlar',
            },
        ),
    ]
