# Generated by Django 4.1 on 2022-09-01 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0002_homepage_alter_aboutus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses_nomber', models.CharField(max_length=50)),
                ('section', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/about/')),
            ],
            options={
                'verbose_name': 'Mavzu',
                'verbose_name_plural': 'Mavzular',
            },
        ),
    ]
