# Generated by Django 4.1 on 2022-09-01 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0004_courses_alter_subjects_courses_nomber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
    ]
