# Generated by Django 4.1 on 2022-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0005_alter_courses_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='students',
            field=models.IntegerField(max_length=30),
        ),
    ]
