# Generated by Django 4.1 on 2022-09-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0006_alter_courses_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='students',
            new_name='student',
        ),
    ]
