# Generated by Django 4.1 on 2022-09-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0008_rename_student_courses_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('text', models.TextField(max_length=500)),
                ('section', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='media/subjects/')),
            ],
            options={
                'verbose_name': 'Avtorizatsiya',
                'verbose_name_plural': 'Avtorizatsiyalar',
            },
        ),
    ]
