# Generated by Django 4.1 on 2022-09-01 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0009_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'Yangilik', 'verbose_name_plural': 'Yangiliklar'},
        ),
    ]
