# Generated by Django 4.1 on 2022-09-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0010_alter_students_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='section',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='students',
            name='text',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='students',
            name='title',
            field=models.TextField(max_length=50),
        ),
    ]
