# Generated by Django 4.1 on 2022-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0011_alter_students_section_alter_students_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=54)),
                ('course', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Royxatdan o`tish`',
                'verbose_name_plural': 'Ro`yxatgan o`tganlar',
            },
        ),
    ]
