# Generated by Django 4.1 on 2022-09-01 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0012_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('jobs', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
            ],
            options={
                'verbose_name': 'O`qituvchi',
                'verbose_name_plural': 'O`qituvchilar',
            },
        ),
    ]
