# Generated by Django 4.1 on 2022-09-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0013_teachers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
                ('lavel', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'O`qituvchi',
                'verbose_name_plural': 'O`qituvchilar',
            },
        ),
    ]
