# Generated by Django 4.1 on 2022-09-01 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0014_testimonial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonial',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professorlar'},
        ),
    ]
