# Generated by Django 4.1 on 2022-09-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0015_alter_testimonial_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('data', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/Teachers/')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professorlar',
            },
        ),
    ]
